export type LoginResquest = {
	mobile : string
	password : string
}

export type LoginResponse = {
	id : string
	username : string
}

export type RegisterResquest = {
	username : string
	password : string
	mobile : string
}

export type RegisterResponse = {
	id : string
	username : string
}

export type UserRow = {
	_id : string
	username : string
	password : string
	mobile : string
	status : number
	create_time : string
}